name: tampon

services:
  atelier:
    container_name: tampon-atelier
    build:
      context: ..
      dockerfile: docker/atelier/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../tirages:/app/tirages
      - ../logs:/app/logs
    restart: unless-stopped
